version: '3.8'
services:

  db:
    image: postgres:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    
  web:
    image: igorkalchenko/foodgram_back:latest
    restart: always
    ports: 
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: igorkalchenko/foodgram_front:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - web

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - web

volumes:
  static_value:
  media_value:
  postgres_data:
