# Generated by Django 2.2.16 on 2022-10-25 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='subscribe_constraints',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_subscribed',
        ),
        migrations.AddField(
            model_name='subscription',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='subscribe_constraints'),
        ),
    ]
