# Generated by Django 2.2.16 on 2022-11-05 15:52

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221030_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150, validators=[api.validators.OnlyLettersValidator], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=150, validators=[api.validators.OnlyLettersValidator], verbose_name='last name'),
        ),
    ]
